using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using APIFramework.Components;
using APIFramework.Core;
using Xunit;

namespace APIFramework.Tests.Performance;

/// <summary>
/// Diagnoses the "many systems show ~315 bytes / call" pattern surfaced by the
/// per-system allocation profile in `SystemBenchmarkBaselineTests`. Investigates
/// whether the floor is measurement-framework overhead (lambdas, list rentals
/// in our own benchmark code) OR real per-Update overhead inside `EntityManager.Query<T>()`
/// or related hot paths.
///
/// METHOD
/// ──────
/// Run isolated allocation measurements against:
///   1. A NoOpSystem — Update method that does literally nothing.
///   2. A QueryOnlySystem — Update calls em.Query&lt;T&gt;().Count() exactly once.
///   3. A QueryEnumerateSystem — Update enumerates a Query&lt;T&gt;() result fully.
///
/// If (1) reports > 0 bytes/call: overhead is in our measurement framework.
/// If (1) reports 0 and (2) > 0: overhead is in EntityManager.Query.
/// If (2) reports 0 and (3) > 0: overhead is in the IEnumerable enumeration.
///
/// FINDINGS
/// ────────
/// Recorded as test output (xUnit ITestOutputHelper). Ship as informational
/// fixture — actionable for any future allocation-reduction packet.
/// </summary>
public class AllocationHotPathInvestigationTests
{
    private const int   AllocSampleIterations = 200;
    private const float TickDelta             = 1f;

    /// <summary>System that does nothing. Baseline for "what does invoking Update cost?"</summary>
    private sealed class NoOpSystem : ISystem
    {
        public void Update(EntityManager em, float deltaTime) { }
    }

    /// <summary>System that calls Query&lt;T&gt;().Count() — measures dispatch + Linq.Count overhead.</summary>
    private sealed class QueryOnlySystem : ISystem
    {
        public void Update(EntityManager em, float deltaTime)
        {
            _ = em.Query<MetabolismComponent>().Count();
        }
    }

    /// <summary>System that enumerates Query&lt;T&gt;() fully — measures enumeration cost.</summary>
    private sealed class QueryEnumerateSystem : ISystem
    {
        public void Update(EntityManager em, float deltaTime)
        {
            int n = 0;
            foreach (var e in em.Query<MetabolismComponent>()) n++;
            _ = n;
        }
    }

    /// <summary>System that calls Query AND Get on the resulting entities — closest to real-system pattern.</summary>
    private sealed class QueryAndGetSystem : ISystem
    {
        public void Update(EntityManager em, float deltaTime)
        {
            float total = 0f;
            foreach (var e in em.Query<MetabolismComponent>())
            {
                var meta = e.Get<MetabolismComponent>();
                total += meta.Satiation;
            }
            _ = total;
        }
    }

    [Fact]
    public void Investigation_GenerateAllocationHotPathFixture()
    {
        // Probe 1: per-system-template allocation breakdown at humanCount=30.
        var sim30 = new SimulationBootstrapper(humanCount: 30);
        var em30  = sim30.EntityManager;
        var noop          = MeasureAllocPerCall(new NoOpSystem(),          em30);
        var queryOnly     = MeasureAllocPerCall(new QueryOnlySystem(),     em30);
        var queryEnumerate= MeasureAllocPerCall(new QueryEnumerateSystem(),em30);
        var queryAndGet   = MeasureAllocPerCall(new QueryAndGetSystem(),   em30);

        // Probe 2: NPC-count scaling.
        var scaling = new List<(int NpcCount, long Noop, long QueryOnly, long QueryAndGet)>();
        foreach (var n in new[] { 1, 10, 30, 60, 100 })
        {
            var sim = new SimulationBootstrapper(humanCount: n);
            var em  = sim.EntityManager;
            scaling.Add((n,
                MeasureAllocPerCall(new NoOpSystem(),        em),
                MeasureAllocPerCall(new QueryOnlySystem(),   em),
                MeasureAllocPerCall(new QueryAndGetSystem(), em)));
        }

        // Build the fixture markdown.
        var sb = new StringBuilder();
        sb.AppendLine("# allocation-hot-paths.md");
        sb.AppendLine("# Generated by AllocationHotPathInvestigationTests on every test run.");
        sb.AppendLine($"# Run timestamp (UTC): {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine("Diagnoses the per-system allocation floor surfaced by `system-baselines.md`. ");
        sb.AppendLine("Probes minimal ISystem implementations to pinpoint where bytes/call comes from.");
        sb.AppendLine();
        sb.AppendLine("## Probe 1 — Allocation by Update body shape (humanCount=30)");
        sb.AppendLine();
        sb.AppendLine("| Probe system | Update body | bytes / call |");
        sb.AppendLine("|:---|:---|---:|");
        sb.AppendLine($"| NoOpSystem | (empty)                                      | {noop,5} |");
        sb.AppendLine($"| QueryOnlySystem | em.Query<MetabolismComponent>().Count() | {queryOnly,5} |");
        sb.AppendLine($"| QueryEnumerateSystem | foreach over Query result          | {queryEnumerate,5} |");
        sb.AppendLine($"| QueryAndGetSystem | foreach + Get<T>() per entity         | {queryAndGet,5} |");
        sb.AppendLine();
        sb.AppendLine("**Interpretation guide:**");
        sb.AppendLine("- `NoOp > 0` → overhead lives in the measurement framework or the JIT loop, not in any system code. The per-system numbers in `system-baselines.md` should be read as *additional* cost on top of this floor.");
        sb.AppendLine("- `QueryOnly > NoOp` → `EntityManager.Query<T>()` itself allocates per call (likely Linq's `Count()` boxing the enumerator).");
        sb.AppendLine("- `QueryEnumerate > QueryOnly` → `foreach` over the Query result allocates an enumerator each iteration.");
        sb.AppendLine("- `QueryAndGet > QueryEnumerate` → `Entity.Get<T>()` adds per-component-access cost.");
        sb.AppendLine();
        sb.AppendLine("## Probe 2 — Allocation scaling with NPC count");
        sb.AppendLine();
        sb.AppendLine("| NPC count | NoOp | QueryOnly | QueryAndGet |");
        sb.AppendLine("|----------:|-----:|----------:|------------:|");
        foreach (var row in scaling)
            sb.AppendLine($"| {row.NpcCount,9} | {row.Noop,4} | {row.QueryOnly,9} | {row.QueryAndGet,11} |");
        sb.AppendLine();
        sb.AppendLine("**Interpretation guide:**");
        sb.AppendLine("- If `QueryAndGet` bytes/call grows with NPC count, the per-system overhead is proportional to entity count (likely buffer/enumerator allocation tied to result size). High-NPC scenarios then pay more per system per tick — direct input for any future Query-path optimization.");
        sb.AppendLine("- If bytes/call is roughly constant across NPC counts, overhead is fixed per-call (e.g., a single iterator state object) — cheaper at scale than data-proportional allocation.");
        sb.AppendLine();
        sb.AppendLine("## Action items (for any future allocation-reduction packet)");
        sb.AppendLine();
        sb.AppendLine("1. If `NoOp > 0`: investigate the measurement harness for hidden allocations (loop-local closures, Stopwatch.Restart implementation).");
        sb.AppendLine("2. If `QueryOnly` accounts for most of the per-system floor: provide a non-Linq variant of `Query<T>()` returning a struct enumerator, OR add a `QueryCount<T>()` fast-path.");
        sb.AppendLine("3. If `QueryEnumerate > QueryOnly` by a non-trivial margin: the foreach pattern boxes the IEnumerator. Adding `IEnumerable<Entity>.GetEnumerator()` returning a struct enumerator (or providing an explicit struct enumerator method) eliminates the box.");
        sb.AppendLine("4. The numbers here calibrate the ROI of any Query-path optimization. If the floor is 50 bytes/system × 50 systems × 60 FPS = 150KB/sec — meaningful but not urgent. If it's 500 bytes/system × etc → much larger payoff.");

        // Write fixture next to the perf baseline.
        var path = LocateFixturePath();
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, sb.ToString());

        Assert.True(File.Exists(path), $"Fixture file should exist at {path}");

        // No noop-allocation sanity assertion here. `GC.GetTotalAllocatedBytes(precise: true)`
        // is process-wide and contaminated by concurrent tests under parallel xUnit
        // execution; even a 100 KB threshold flaked occasionally. The fixture itself
        // is the diagnostic — clean isolated runs show NoOp = 0 bytes (proves harness
        // is leak-free); noisy parallel runs show contamination but the relative
        // ordering between probes (NoOp < QueryOnly < QueryEnumerate) stays valid.
        //
        // For clean per-call numbers, run isolated:
        //   dotnet test --filter "FullyQualifiedName~AllocationHotPath"
        // We use `noop` here just to silence the unused-variable warning.
        _ = noop;
    }

    private static string LocateFixturePath()
    {
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        for (int i = 0; i < 8; i++)
        {
            if (dir is null) break;
            var candidate = Path.Combine(
                dir.FullName,
                "APIFramework.Tests", "Performance", "PerformanceFixtures", "allocation-hot-paths.md");
            if (Directory.Exists(Path.GetDirectoryName(candidate)!)
                || Directory.Exists(Path.GetDirectoryName(Path.GetDirectoryName(candidate)!)!))
                return candidate;
            dir = dir.Parent;
        }
        return Path.Combine(Path.GetTempPath(), "allocation-hot-paths.md");
    }

    // ── Measurement primitive ────────────────────────────────────────────────────

    private static long MeasureAllocPerCall(ISystem system, EntityManager em)
    {
        // Warm up
        for (int i = 0; i < 5; i++) system.Update(em, TickDelta);

        GC.Collect();
        GC.WaitForPendingFinalizers();
        GC.Collect();
        long allocBefore = GC.GetTotalAllocatedBytes(precise: true);

        for (int i = 0; i < AllocSampleIterations; i++)
            system.Update(em, TickDelta);

        long allocAfter = GC.GetTotalAllocatedBytes(precise: true);
        return (allocAfter - allocBefore) / AllocSampleIterations;
    }
}
