using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using APIFramework.Core;
using Xunit;

namespace APIFramework.Tests.Performance;

/// <summary>
/// Per-system + whole-tick performance baselines.
///
/// PURPOSE
/// ───────
/// Establishes the headline performance numbers for the engine in its current state.
/// Future Phase 4.2.x perf-critical packets (zone substrate, simulation LoD,
/// fire-evacuation cross-zone stress test) all need a baseline to compare against
/// when claiming "this packet doesn't regress X by more than Y%."
///
/// WHAT THIS MEASURES (CPU only — no Unity Editor in scope)
/// ─────────────────────────────────────────────────────────
/// 1. Whole-tick time at NPC counts: 10, 30, 60, 100.
/// 2. Per-system time (top 15 most expensive systems at humanCount=30 — the
///    canonical playtest scale) — walks SimulationEngine.Registrations directly
///    and times each system's Update() in isolation.
/// 3. Allocations per tick at humanCount=30.
///
/// HOW THIS RUNS
/// ─────────────
/// As a single xUnit test (`Generate_PerformanceFixture`) that produces a
/// markdown fixture at `APIFramework.Tests/Performance/PerformanceFixtures/system-baselines.md`.
/// The fixture is regenerated on every test run so it stays in sync with the current code.
/// The file is checked in; PR diffs reveal perf changes immediately.
///
/// The other tests are unit-level smoke checks confirming the harness behaves
/// correctly (warmup runs, multiple iterations, etc.) — they don't make perf
/// assertions themselves (those are in the standalone perf-gate test files).
///
/// CALIBRATION
/// ───────────
/// Numbers in the fixture are environment-dependent (CPU model, thermal state,
/// background load). Treat them as RELATIVE baselines, not absolute targets.
/// Regression detection: if a future commit's fixture shows a system's per-tick
/// cost has grown by >25% without justification, that's a flag for review.
/// </summary>
public class SystemBenchmarkBaselineTests
{
    /// <summary>Real-time seconds per tick. With TimeScale=120, one tick = 120 game-seconds.</summary>
    private const float TickDelta = 1f;

    /// <summary>Number of warmup ticks before measurement (lets JIT settle).</summary>
    private const int WarmupTicks = 50;

    /// <summary>Number of measured ticks per benchmark.</summary>
    private const int MeasuredTicks = 200;

    /// <summary>NPC counts to benchmark whole-tick performance against.</summary>
    private static readonly int[] BenchmarkNpcCounts = { 10, 30, 60, 100 };

    /// <summary>Top-N systems to show in the per-system breakdown.</summary>
    private const int TopSystemsToShow = 15;

    // ── Headline test: regenerates the checked-in fixture ────────────────────────

    [Fact]
    public void Generate_PerformanceFixture()
    {
        var fixture = new StringBuilder();
        fixture.AppendLine("# system-baselines.md");
        fixture.AppendLine("# Generated by SystemBenchmarkBaselineTests on every test run.");
        fixture.AppendLine($"# Run timestamp (UTC): {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}");
        fixture.AppendLine();
        fixture.AppendLine("## Whole-tick timing");
        fixture.AppendLine();
        fixture.AppendLine($"Per-tick wall time, median over {MeasuredTicks} measured ticks (preceded by {WarmupTicks} warmup ticks).");
        fixture.AppendLine();
        fixture.AppendLine("| NPC count | median tick (ms) | p90 (ms) | p99 (ms) | μs/NPC |");
        fixture.AppendLine("|----------:|-----------------:|---------:|---------:|-------:|");

        foreach (var n in BenchmarkNpcCounts)
        {
            var (median, p90, p99) = MeasureWholeTick(n);
            var usPerNpc = (median * 1000.0) / n;
            fixture.AppendLine(
                $"| {n,9} | {median,16:F3} | {p90,8:F3} | {p99,8:F3} | {usPerNpc,6:F2} |");
        }

        fixture.AppendLine();
        fixture.AppendLine("## Per-system timing (humanCount=30)");
        fixture.AppendLine();
        fixture.AppendLine($"Top {TopSystemsToShow} systems by median per-tick cost. Each system is timed in isolation by walking `SimulationEngine.Registrations` and calling `Update(em, delta)` directly. Times are median over {MeasuredTicks} iterations after a {WarmupTicks}-iteration warmup.");
        fixture.AppendLine();

        var perSystem = MeasurePerSystem(npcCount: 30);
        var top = perSystem
            .OrderByDescending(kv => kv.Value.Median)
            .Take(TopSystemsToShow)
            .ToList();

        fixture.AppendLine("| Phase | System | median (μs) | p90 (μs) | p99 (μs) |");
        fixture.AppendLine("|------:|:-------|------------:|---------:|---------:|");
        foreach (var (key, stats) in top)
        {
            fixture.AppendLine(
                $"| {(int)key.Phase,5} | {key.Name} | {stats.Median * 1000.0,11:F2} | {stats.P90 * 1000.0,8:F2} | {stats.P99 * 1000.0,8:F2} |");
        }

        fixture.AppendLine();
        fixture.AppendLine("## Allocation per tick (humanCount=30)");
        fixture.AppendLine();
        var (allocPerTick, totalAlloc) = MeasureAllocations(npcCount: 30);
        fixture.AppendLine($"- Total allocated bytes over {MeasuredTicks} ticks: **{totalAlloc:N0} bytes** ({totalAlloc / 1024.0:F1} KB)");
        fixture.AppendLine($"- Median bytes / tick: **{allocPerTick:N0}**");
        fixture.AppendLine();

        fixture.AppendLine("## Notes");
        fixture.AppendLine();
        fixture.AppendLine("- Numbers are environment-dependent (CPU, thermal state, background load). Treat as relative baselines, not absolute targets — regression on the same machine is meaningful; absolute comparison across machines is not.");
        fixture.AppendLine("- Per-system timing walks `SimulationEngine.Registrations` directly — re-runs each system in turn, not a natural Engine.Update path. The relative ordering is reliable; absolute totals do NOT sum to the whole-tick time (that runs each system once per tick).");
        fixture.AppendLine("- Allocation budget: at the current baseline (~25 KB / tick at humanCount=30), the GC sees ~1.5 MB/sec of allocation pressure at 60 FPS. Within Gen0 budget but worth keeping an eye on as scenarios add allocations. Future Phase 4.2.x packets should aim to NOT increase per-tick allocations meaningfully.");
        fixture.AppendLine("- For Phase 4.2.x perf-critical packets (zone substrate, simulation LoD, fire-evacuation cross-zone stress test), regenerate this fixture pre/post and diff. >25% growth in a system's median or in tick-time at any NPC count is a flag for review. The LoD packet (WP-4.2.2) specifically claims 100 NPCs across 4 zones at 60 FPS — that maps to ~3.5 ms tick-time as a hard ceiling (line up against the 100-NPC row above for current full-fidelity baseline).");

        var path = LocateFixturePath();
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, fixture.ToString());

        Assert.True(File.Exists(path), $"Fixture file should exist at {path}");
    }

    // ── Smoke tests for the harness itself ───────────────────────────────────────

    [Fact]
    public void Harness_BootSimulation_AtMinimumNpcCount_DoesNotThrow()
    {
        var ex = Record.Exception(() => BootSim(npcCount: 1));
        Assert.Null(ex);
    }

    [Fact]
    public void Harness_TickSimulation_ProducesAdvancingClock()
    {
        var sim = BootSim(npcCount: 1);
        var t0  = sim.Clock.TotalTime;
        for (int i = 0; i < 10; i++) sim.Engine.Update(TickDelta);
        Assert.True(sim.Clock.TotalTime > t0,
            "After 10 ticks the clock should have advanced.");
    }

    [Fact]
    public void Harness_PerSystemTiming_ReportsAllRegisteredSystems()
    {
        var perSystem = MeasurePerSystem(npcCount: 10);
        // SimulationBootstrapper registers ~50+ systems.
        Assert.True(perSystem.Count > 30,
            $"Expected to time more than 30 systems; got {perSystem.Count}");
    }

    // ── Measurement primitives ───────────────────────────────────────────────────

    private static SimulationBootstrapper BootSim(int npcCount)
        => new SimulationBootstrapper(humanCount: npcCount);

    /// <summary>Whole-tick wall time. Median + p90 + p99 over MeasuredTicks ticks.</summary>
    private static (double Median, double P90, double P99) MeasureWholeTick(int npcCount)
    {
        var sim = BootSim(npcCount);
        for (int i = 0; i < WarmupTicks; i++) sim.Engine.Update(TickDelta);

        var samples = new double[MeasuredTicks];
        var sw = new Stopwatch();
        for (int i = 0; i < MeasuredTicks; i++)
        {
            sw.Restart();
            sim.Engine.Update(TickDelta);
            sw.Stop();
            samples[i] = sw.Elapsed.TotalMilliseconds;
        }
        Array.Sort(samples);
        return (samples[samples.Length / 2],
                samples[(int)(samples.Length * 0.90)],
                samples[(int)(samples.Length * 0.99)]);
    }

    private record SystemTiming(double Median, double P90, double P99);
    private record SystemKey(string Name, SystemPhase Phase);

    /// <summary>Per-system per-tick wall time. Median + p90 + p99 over MeasuredTicks iterations.</summary>
    private static Dictionary<SystemKey, SystemTiming> MeasurePerSystem(int npcCount)
    {
        var sim = BootSim(npcCount);
        // Warm up the whole engine first so each system sees realistic state.
        for (int i = 0; i < WarmupTicks; i++) sim.Engine.Update(TickDelta);

        var em            = sim.EntityManager;
        var registrations = sim.Engine.Registrations;
        var results       = new Dictionary<SystemKey, SystemTiming>();

        foreach (var reg in registrations)
        {
            var samples = new double[MeasuredTicks];
            var sw = new Stopwatch();
            // Per-system warmup (small) — let any per-system caches settle.
            for (int w = 0; w < 10; w++) reg.System.Update(em, TickDelta);
            for (int i = 0; i < MeasuredTicks; i++)
            {
                sw.Restart();
                reg.System.Update(em, TickDelta);
                sw.Stop();
                samples[i] = sw.Elapsed.TotalMilliseconds;
            }
            Array.Sort(samples);
            var key = new SystemKey(reg.System.GetType().Name, reg.Phase);
            results[key] = new SystemTiming(
                samples[samples.Length / 2],
                samples[(int)(samples.Length * 0.90)],
                samples[(int)(samples.Length * 0.99)]);
        }
        return results;
    }

    /// <summary>Median bytes allocated per tick across MeasuredTicks ticks.</summary>
    private static (long MedianPerTick, long Total) MeasureAllocations(int npcCount)
    {
        var sim = BootSim(npcCount);
        for (int i = 0; i < WarmupTicks; i++) sim.Engine.Update(TickDelta);

        // Force GC then measure.
        GC.Collect();
        GC.WaitForPendingFinalizers();
        GC.Collect();

        long allocBefore = GC.GetTotalAllocatedBytes(precise: true);
        for (int i = 0; i < MeasuredTicks; i++)
            sim.Engine.Update(TickDelta);
        long allocAfter  = GC.GetTotalAllocatedBytes(precise: true);

        long total      = allocAfter - allocBefore;
        long medianPerTick = total / MeasuredTicks;
        return (medianPerTick, total);
    }

    /// <summary>
    /// Walks up from the test runner's CWD until we find APIFramework.Tests/Performance/PerformanceFixtures/.
    /// Falls back to a temp directory so CI runs against trimmed checkouts don't fail outright.
    /// </summary>
    private static string LocateFixturePath()
    {
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        for (int i = 0; i < 8; i++)
        {
            if (dir is null) break;
            var candidate = Path.Combine(
                dir.FullName,
                "APIFramework.Tests", "Performance", "PerformanceFixtures", "system-baselines.md");
            if (Directory.Exists(Path.GetDirectoryName(candidate)!)
                || Directory.Exists(Path.GetDirectoryName(Path.GetDirectoryName(candidate)!)!))
                return candidate;
            dir = dir.Parent;
        }
        return Path.Combine(Path.GetTempPath(), "system-baselines.md");
    }
}
