using System;
using System.IO;
using System.Text;
using APIFramework.Cast;
using Xunit;

namespace APIFramework.Tests.Cast;

/// <summary>
/// Generates the human-readable sample-roll fixture. Talon reviews periodically for absurdity
/// calibration; if the fixture changes (catalog content edits), the diff is the audit trail.
///
/// The fixture is regenerated on every test run so it stays in sync with whatever the current
/// catalog produces. The test asserts the file exists at the expected location after generation.
/// </summary>
public class SampleRollFixtureTests
{
    [Fact]
    public void Generate_SampleRolls_WritesFixtureFile()
    {
        var data = CastNameDataLoader.LoadDefault()!;
        var gen  = new CastNameGenerator(data);
        var rng  = new Random(42);

        var sb = new StringBuilder();
        sb.AppendLine("# sample-1000-rolls.txt");
        sb.AppendLine("# Generated by SampleRollFixtureTests with seed 42.");
        sb.AppendLine("# Format: [tier] gender:title? displayName");
        sb.AppendLine();

        for (int i = 0; i < 1000; i++)
        {
            var r = gen.Generate(rng);
            var titleField = r.Title is null ? "" : $" title:'{r.Title}'";
            sb.Append('[').Append(r.Tier.ToString().ToLowerInvariant().PadRight(9)).Append("] ")
              .Append(r.Gender.ToString().ToLowerInvariant().PadRight(7))
              .Append(titleField)
              .Append(' ')
              .AppendLine(r.DisplayName);
        }

        var dir = LocateFixtureDirectory();
        Directory.CreateDirectory(dir);
        var path = Path.Combine(dir, "sample-1000-rolls.txt");
        File.WriteAllText(path, sb.ToString());

        Assert.True(File.Exists(path), $"Fixture not written: {path}");

        var lines = File.ReadAllLines(path);
        // 4 header lines + 1000 data lines
        Assert.Equal(1004, lines.Length);
    }

    /// <summary>
    /// Walks up from the test runner's CWD until we find APIFramework.Tests/Cast/SampleRollFixtures/.
    /// If not found, falls back to a sibling of the test assembly so CI runs don't fail on
    /// non-checked-out trees.
    /// </summary>
    private static string LocateFixtureDirectory()
    {
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        for (int i = 0; i < 8; i++)
        {
            if (dir is null) break;
            var candidate = Path.Combine(
                dir.FullName,
                "APIFramework.Tests", "Cast", "SampleRollFixtures");
            if (Directory.Exists(Path.GetDirectoryName(candidate)!)) return candidate;
            dir = dir.Parent;
        }
        return Path.Combine(Path.GetTempPath(), "cast-sample-rolls");
    }
}
