using System.Text.Json.Serialization;

namespace Warden.Anthropic;

/// <summary>
/// Response body from <c>POST /v1/messages</c>.
/// </summary>
/// <param name="Id">Unique message identifier, e.g. <c>"msg_01XFDUDYJgAACzvnptvVoYEL"</c>.</param>
/// <param name="Type">Always <c>"message"</c> for this endpoint.</param>
/// <param name="Role">Always <c>"assistant"</c> for this endpoint.</param>
/// <param name="Content">The model's output content blocks.</param>
/// <param name="Model">The model that produced this response.</param>
/// <param name="StopReason">Why the model stopped: <c>"end_turn"</c>, <c>"max_tokens"</c>, <c>"stop_sequence"</c>, or <c>"tool_use"</c>.</param>
/// <param name="StopSequence">The stop sequence that caused the halt, if applicable.</param>
/// <param name="Usage">Token usage breakdown including cache metrics.</param>
public sealed record MessageResponse(
    string             Id,
    string             Type,
    string             Role,
    List<ContentBlock> Content,
    ModelId            Model,
    [property: JsonPropertyName("stop_reason")]    string?     StopReason,
    [property: JsonPropertyName("stop_sequence")]  string?     StopSequence,
    TokenUsage         Usage);

/// <summary>
/// Token usage counters returned with every <see cref="MessageResponse"/>.
/// Cache metrics are zero when prompt caching is not active.
/// </summary>
/// <param name="InputTokens">Non-cached input tokens charged at the full input rate.</param>
/// <param name="CacheCreationInputTokens">Tokens written to the prompt cache (charged at 1.25× input rate).</param>
/// <param name="CacheReadInputTokens">Tokens read from the prompt cache (charged at 0.10× input rate).</param>
/// <param name="OutputTokens">Output tokens generated by the model.</param>
public sealed record TokenUsage(
    [property: JsonPropertyName("input_tokens")]                int InputTokens,
    [property: JsonPropertyName("cache_creation_input_tokens")] int CacheCreationInputTokens,
    [property: JsonPropertyName("cache_read_input_tokens")]     int CacheReadInputTokens,
    [property: JsonPropertyName("output_tokens")]               int OutputTokens);
